[package]
name = "terminal"
version = "0.0.0"
edition.workspace = true
license.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
which = { workspace = true }

[lints]
workspace = true
