[package]
name = "tray"
version = "0.0.0"
edition.workspace = true
license.workspace = true

[dependencies]
config = { workspace = true }
tray-icon = { workspace = true }
image = { workspace = true }

[lints]
workspace = true
